version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.5
    container_name: fastapi-postgres
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
