version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.5-alpine
    container_name: fastapi-postgres
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
  
  fastapi-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-webserver
    env_file: .env.example
    ports:
      - 8000:8000
    command: bash -c "cd /app && alembic upgrade head && cd /app/src && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
