[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = 'tests|migrations|logger'

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ["tests", "migrations"]

[mypy]
ignore_missing_imports = true
